# 1. Create a 3x3x3 array with random values

In [2]:
import numpy as np

In [10]:
x=np.random.rand(3,3,3)
print(x)

[[[0.08748779 0.31161287 0.53018974]
  [0.77147346 0.5866379  0.40178836]
  [0.48171336 0.07473948 0.36704468]]

 [[0.66076242 0.73324348 0.25943681]
  [0.22400682 0.15204364 0.57297676]
  [0.73344149 0.51129305 0.89861053]]

 [[0.58183046 0.72409661 0.796132  ]
  [0.8666418  0.41767737 0.85285043]
  [0.40068806 0.02740544 0.27777017]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [11]:
x = np.diag([1, 2, 3, 4], k=-1)

print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [17]:
x = np.zeros((8, 8), dtype=int)

x[1::2, ::2] = 1  
x[::2, 1::2] = 1  

print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [18]:
x = np.random.rand(5, 5)


mean = np.mean(x)
std_dev = np.std(x)


normalized_x = (x - mean) / std_dev

print("Original Matrix:")
print(x)
print("\nNormalized Matrix:")
print(normalized_x)

Original Matrix:
[[0.70406538 0.11961542 0.25532786 0.24509001 0.51624099]
 [0.25868371 0.7691154  0.77855642 0.44954567 0.06800856]
 [0.84769443 0.36912747 0.76919688 0.52684763 0.80226578]
 [0.65116793 0.71063194 0.45722908 0.92996179 0.49127938]
 [0.5448749  0.78059463 0.7367075  0.20609846 0.01600648]]

Normalized Matrix:
[[ 0.70264283 -1.53031881 -1.01181303 -1.05092798 -0.01496293]
 [-0.99899161  0.95117429  0.98724485 -0.26978043 -1.72748903]
 [ 1.25139497 -0.57702788  0.95148562  0.02556102  1.07782934]
 [ 0.50054174  0.7277312  -0.24042505  1.56570734 -0.11033175]
 [ 0.09443639  0.9950321   0.82735599 -1.19989989 -1.92616927]]


# 5. How to find common values between two arrays?

In [19]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(array1, array2)

print("Common Values:", common_values)

Common Values: [3 4 5]


# 6. How to get the dates of yesterday, today and tomorrow?

In [20]:
import numpy as np
from datetime import datetime, timedelta

today = datetime.now().date()

date_range = np.array([today - timedelta(days=1), today, today + timedelta(days=1)], dtype='datetime64[D]')

print("Yesterday:", date_range[0])
print("Today:", date_range[1])
print("Tomorrow:", date_range[2])


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, check if they are equal

In [25]:
A = np.ones((5, 5))
B = np.ones((5, 5))

# Check if the arrays are equal
are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are equal.


In [28]:
print(A,"\n\n",B)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# 8.Create random vector of size 10 and replace the maximum value by 0

In [31]:
random_vector = np.random.rand(10)

max_value = np.max(random_vector)
print(max_value)
max_index = np.argmax(random_vector)
print(max_index)
random_vector[max_index] = 0
print("Original Random Vector:")
print(random_vector)

0.9264276803642959
7
Original Random Vector:
[0.47721152 0.45310342 0.2171504  0.46234374 0.490807   0.12102693
 0.09568224 0.         0.77561682 0.06561963]


# 9. How to print all the values of an array?

In [30]:

my_array = np.array([1, 2, 3, 4, 5])

for item in my_array:
    print(item)


1
2
3
4
5


# 10.Subtract the mean of each row of a matrix

In [34]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_means = np.mean(matrix, axis=1, keepdims=True)
print(row_means)

matrix_minus_means = matrix - row_means

print("Original Matrix:")
print(matrix)
print("\nMatrix with Row Means Subtracted:")
print(matrix_minus_means)


[[2.]
 [5.]
 [8.]]
Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [35]:
# Given vector
vector = np.array([1, 2, 3, 4, 5])

# Second vector containing indices
indices = np.array([1, 3, 3, 4])

# Create a boolean mask for unique indices
unique_indices = np.unique(indices)
print(unique_indices)
# Add 1 to the elements at unique indices
vector[unique_indices] += 1

print("Modified Vector:")
print(vector)


[1 3 4]
Modified Vector:
[1 3 3 5 6]


# 12.How to get the diagonal of a dot product?

In [36]:
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_B = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])


dot_product_result = np.dot(matrix_A, matrix_B)


diagonal = np.diag(dot_product_result)

print("Matrix A:")
print(matrix_A)

print("\nMatrix B:")
print(matrix_B)

print("\nDot Product Result:")
print(dot_product_result)

print("\nDiagonal of Dot Product:")
print(diagonal)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Dot Product Result:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of Dot Product:
[30 69 90]


# 13.How to find the most frequent value in an array?

In [43]:
array = np.array([2, 3, 2, 5, 6, 2, 8, 2, 8, 8, 3])

# Use numpy's unique function to get unique values and their counts
unique_values, counts = np.unique(array, return_counts=True)

print(unique_values,counts)

# Find the index of the maximum count (most frequent value)
most_frequent_index = np.argmax(counts)

print(most_frequent_index)

# Get the most frequent value
most_frequent_value = unique_values[most_frequent_index]

print("Array:", array)
print("Most Frequent Value:", most_frequent_value)


[2 3 5 6 8] [4 2 1 1 3]
0
Array: [2 3 2 5 6 2 8 2 8 8 3]
Most Frequent Value: 2


# 14.How to get the n largest values of an array

In [45]:
array = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

# Specify the number of largest values (n)
n = 3

# Use np.argsort to get the indices that would sort the array
sorted_indices = np.argsort(array)
print(sorted_indices)

# Get the n largest values by indexing into the sorted array
n_largest_values = array[sorted_indices[-n:]]

print("Array:", array)
print(f"{n} Largest Values:", n_largest_values)


[1 3 6 0 9 2 4 8 7 5]
Array: [3 1 4 1 5 9 2 6 5 3]
3 Largest Values: [5 6 9]


# 15. How to create a record array from a regular array?

In [46]:
import numpy as np

# Create a regular array
regular_array = np.array([(1, 'Alice', 25),
                          (2, 'Bob', 30),
                          (3, 'Charlie', 28)],
                         dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])

# Create a record array from the regular array
record_array = np.rec.fromarrays(regular_array.T, names=regular_array.dtype.names)

print("Regular Array:")
print(regular_array)

print("\nRecord Array:")
print(record_array)


Regular Array:
[(1, 'Alice', 25) (2, 'Bob', 30) (3, 'Charlie', 28)]

Record Array:
((1, 'Alice', 25), (2, 'Bob', 30), (3, 'Charlie', 28))


# 16. How to swap two rows of an array?

In [52]:
import numpy as np

# Create a sample 2D array (replace this with your own array)
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Define the indices of the rows to swap
row1_index = 1  # Index of the first row (0-based)
row2_index = 2  # Index of the second row (0-based)

# Create temporary variables to hold the rows to be swapped
temp_row = array[row1_index].copy()
array[row1_index] = array[row2_index]
array[row2_index] = temp_row

print("Array after swapping rows:")
print(array)


Array after swapping rows:
[[1 2 3]
 [7 8 9]
 [4 5 6]]


# 17. Write python code to reshape to the next dimension of numpy array?

In [54]:
x=np.array([[23,34,121],[23,22,67],[686,434,123]])

In [55]:
print(x)

[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]


In [62]:
reshaped_x = x.reshape(x.shape[0], x.shape[1], 1)

print("Original Array:")
print(x)

print("\nReshaped Array:")
print(reshaped_x)

Original Array:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]

Reshaped Array:
[[[ 23]
  [ 34]
  [121]]

 [[ 23]
  [ 22]
  [ 67]]

 [[686]
  [434]
  [123]]]


# Case study

In [67]:
olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13,7,11])
olympic_country_silver = np.array([17,28,25,28,8,14,11])
olympic_country_Bronze = np.array([19,22,32,29,7,17,14])

# 1.find the country index with maximum gold

In [68]:
max_gold_index = np.argmax(olympic_country_gold)
print(max_gold_index)
# Get the country name with the maximum gold medals
country_with_max_gold = olympic_country[max_gold_index]

print(f"The country with the maximum gold medals is {country_with_max_gold} at index {max_gold_index}.")

3
The country with the maximum gold medals is US at index 3.


# 3. Find countries with more than 20 gold medals

In [69]:
countries_with_more_than_20_gold = olympic_country[olympic_country_gold > 20]

print("Countries with more than 20 gold medals:")
print(countries_with_more_than_20_gold)

Countries with more than 20 gold medals:
['GBR' 'China' 'RUS' 'US']


# 4. Evaluate the dataset and print the medal:

1. print each country name with number of gold medals

2. print each country nale with total number of medals

In [71]:
total_medals = olympic_country_gold + olympic_country_silver + olympic_country_Bronze

# Print each country name with the number of gold medals
print("Country Name and Number of Gold Medals:")
for country, gold_medals in zip(olympic_country, olympic_country_gold):
    print(f"{country}: {gold_medals} gold medals")

# Print each country name with the total number of medals
print("\nCountry Name and Total Number of Medals:")
for country, total in zip(olympic_country, total_medals):
    print(f"{country}: {total} total medals")

Country Name and Number of Gold Medals:
GBR: 29 gold medals
China: 38 gold medals
RUS: 24 gold medals
US: 46 gold medals
KOR: 13 gold medals
JPN: 7 gold medals
GER: 11 gold medals

Country Name and Total Number of Medals:
GBR: 65 total medals
China: 88 total medals
RUS: 81 total medals
US: 103 total medals
KOR: 28 total medals
JPN: 38 total medals
GER: 36 total medals
