# Develop an image classification model with SVC

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.datasets import load_digits
digits = load_digits()

In [4]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [6]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
df = pd.DataFrame(digits.data,digits.target)
df.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [8]:
df['target'] = digits.target
df.head(20)

0    1     2     3     4     5     6    7    8     9  ...   55   56   57  \
0  0.0  0.0   5.0  13.0   9.0   1.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
1  0.0  0.0   0.0  12.0  13.0   5.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
2  0.0  0.0   0.0   4.0  15.0  12.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
3  0.0  0.0   7.0  15.0  13.0   1.0   0.0  0.0  0.0   8.0  ...  0.0  0.0  0.0   
4  0.0  0.0   0.0   1.0  11.0   0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
5  0.0  0.0  12.0  10.0   0.0   0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
6  0.0  0.0   0.0  12.0  13.0   0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
7  0.0  0.0   7.0   8.0  13.0  16.0  15.0  1.0  0.0   0.0  ...  0.0  0.0  0.0   
8  0.0  0.0   9.0  14.0   8.0   1.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
9  0.0  0.0  11.0  12.0   0.0   0.0   0.0  0.0  0.0   2.0  ...  0.0  0.0  0.0   
0  0.0  0.0   1.0   9.0  15.0  11.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
1  0.0  0.0   0.0   0.0  14.0  13.0   1.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
2  0.0  0.0   5.0  12.0   1.0   0.0   0.0  0.0  0.0   0.0  ...  2.0  0.0  0.0   
3  0.0  2.0   9.0  15.0  14.0   9.0   3.0  0.0  0.0   4.0  ...  0.0  0.0  2.0   
4  0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
5  0.0  5.0  12.0  13.0  16.0  16.0   2.0  0.0  0.0  11.0  ...  0.0  0.0  4.0   
6  0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0  ...  2.0  0.0  0.0   
7  0.0  0.0   1.0   8.0  15.0  10.0   0.0  0.0  0.0   3.0  ...  0.0  0.0  0.0   
8  0.0  0.0  10.0   7.0  13.0   9.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
9  0.0  0.0   6.0  14.0   4.0   0.0   0.0  0.0  0.0   0.0  ...  2.0  0.0  0.0   

     58    59    60    61    62   63  target  
0   6.0  13.0  10.0   0.0   0.0  0.0       0  
1   0.0  11.0  16.0  10.0   0.0  0.0       1  
2   0.0   3.0  11.0  16.0   9.0  0.0       2  
3   7.0  13.0  13.0   9.0   0.0  0.0       3  
4   0.0   2.0  16.0   4.0   0.0  0.0       4  
5   9.0  16.0  16.0  10.0   0.0  0.0       5  
6   1.0   9.0  15.0  11.0   3.0  0.0       6  
7  13.0   5.0   0.0   0.0   0.0  0.0       7  
8  11.0  16.0  15.0  11.0   1.0  0.0       8  
9   9.0  12.0  13.0   3.0   0.0  0.0       9  
0   1.0  10.0  13.0   3.0   0.0  0.0       0  
1   0.0   1.0  13.0  16.0   1.0  0.0       1  
2   3.0  11.0   8.0  13.0  12.0  4.0       2  
3  12.0  12.0  13.0  11.0   0.0  0.0       3  
4   0.0  10.0  15.0   4.0   0.0  0.0       4  
5  15.0  16.0   2.0   0.0   0.0  0.0       5  
6   0.0   7.0  15.0  16.0  11.0  0.0       6  
7   0.0  11.0   9.0   0.0   0.0  0.0       7  
8  11.0  14.0   5.0   0.0   0.0  0.0       8  
9   7.0  16.0  16.0  13.0  11.0  1.0       9  

[20 rows x 65 columns]

In [30]:
x=df.drop('target',axis='columns')
y=df.target

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [38]:
X_train.shape

(1437, 64)

In [39]:
X_test.shape

(360, 64)

# Using RBF kernel

In [40]:
from sklearn.svm import SVC
model = SVC()

In [41]:
model.get_params()

{'C': 1.0,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'rbf',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [42]:
model.fit(X_train, y_train)

SVC()

In [43]:
model.predict(X_test)

array([0, 1, 1, 5, 2, 7, 5, 0, 8, 5, 1, 4, 6, 2, 7, 0, 8, 4, 4, 7, 9, 2,
       4, 0, 1, 9, 1, 2, 4, 1, 4, 0, 9, 3, 6, 7, 6, 3, 4, 5, 1, 8, 9, 0,
       5, 8, 7, 0, 7, 9, 1, 0, 4, 4, 3, 1, 9, 2, 1, 6, 9, 4, 3, 8, 0, 2,
       7, 6, 4, 0, 3, 6, 3, 3, 8, 9, 1, 7, 5, 9, 3, 6, 7, 8, 5, 4, 2, 2,
       6, 3, 2, 1, 5, 9, 5, 3, 1, 4, 1, 7, 0, 2, 7, 5, 8, 3, 1, 8, 3, 3,
       9, 7, 3, 0, 2, 2, 1, 8, 5, 1, 8, 4, 8, 6, 2, 9, 8, 1, 7, 3, 7, 8,
       3, 0, 4, 8, 1, 9, 0, 8, 2, 9, 5, 1, 1, 1, 5, 1, 9, 8, 1, 8, 6, 8,
       3, 8, 2, 9, 3, 2, 3, 9, 1, 7, 3, 6, 4, 8, 7, 0, 8, 5, 6, 6, 6, 4,
       0, 0, 2, 1, 1, 1, 7, 9, 5, 6, 7, 5, 9, 9, 1, 2, 2, 8, 2, 0, 7, 8,
       2, 3, 1, 9, 8, 7, 7, 9, 1, 3, 8, 1, 4, 6, 1, 8, 8, 3, 9, 7, 7, 6,
       2, 3, 5, 8, 2, 5, 4, 9, 9, 3, 1, 6, 6, 7, 8, 0, 9, 2, 7, 4, 4, 3,
       9, 8, 0, 2, 7, 6, 4, 9, 4, 3, 2, 7, 0, 0, 4, 9, 1, 0, 9, 7, 1, 0,
       8, 7, 4, 8, 4, 3, 2, 6, 8, 5, 9, 0, 1, 3, 1, 0, 4, 1, 5, 5, 5, 4,
       3, 3, 1, 9, 5, 3, 5, 2, 4, 3, 1, 1, 3, 2, 6,

In [44]:
model.score(X_test,y_test)

0.9888888888888889

# Using Linear kernel

In [45]:
linear_model = SVC(kernel='linear')
linear_model.fit(X_train,y_train)

SVC(kernel='linear')

In [46]:
linear_model.score(X_test,y_test)

0.9861111111111112