In [1]:
import keras 
from keras.datasets import fashion_mnist
from keras.models import Sequential
from keras.layers import Dense,Dropout
from keras.optimizers import RMSprop

In [2]:
(xtrain,ytrain),(xtest,ytest)=fashion_mnist.load_data()
print(xtrain.shape)
print()
print(ytrain.shape)
print()
print(xtest.shape)
print()
print(ytest.shape)

4422102/4422102 [==============================] - 0s 0us/step
(60000, 28, 28)

(60000,)

(10000, 28, 28)

(10000,)


In [3]:
xtrain=xtrain.reshape(60000,28*28)
xtest=xtest.reshape(10000,28*28)
print(xtrain.shape)
print(xtest.shape)

(60000, 784)
(10000, 784)


In [4]:
xtrain=xtrain.astype('float32')
xtest=xtest.astype('float32')

In [5]:
xtrain=xtrain/255.
xtest=xtest/255.

In [6]:
import keras
num_classes=10
ytrain=keras.utils.to_categorical(ytrain,num_classes)
ytest=keras.utils.to_categorical(ytest,num_classes)

In [7]:
ytrain.shape

(60000, 10)

In [8]:
model=Sequential()
model.add(Dense(512,activation='relu',input_shape=(28*28,)))
model.add(Dense(512,activation='relu'))
model.add(Dense(512,activation='relu'))
model.add(Dense(num_classes,activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 512)               262656    
                                                                 
 dense_2 (Dense)             (None, 512)               262656    
                                                                 
 dense_3 (Dense)             (None, 10)                5130      
                                                                 
Total params: 932362 (3.56 MB)
Trainable params: 932362 (3.56 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
model.compile(loss='categorical_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

In [10]:
history=model.fit(xtrain,ytrain,
                 batch_size=128,
                 epochs=20,
                 verbose=2,
                 validation_data=(xtest,ytest))

score=model.evaluate(xtest,ytest,verbose=1)

Epoch 1/20
469/469 - 7s - loss: 0.5612 - accuracy: 0.7909 - val_loss: 0.5473 - val_accuracy: 0.8083 - 7s/epoch - 16ms/step
Epoch 2/20
469/469 - 7s - loss: 0.3861 - accuracy: 0.8568 - val_loss: 0.4480 - val_accuracy: 0.8386 - 7s/epoch - 14ms/step
Epoch 3/20
469/469 - 7s - loss: 0.3382 - accuracy: 0.8730 - val_loss: 0.4090 - val_accuracy: 0.8497 - 7s/epoch - 14ms/step
Epoch 4/20
469/469 - 7s - loss: 0.3102 - accuracy: 0.8841 - val_loss: 0.3736 - val_accuracy: 0.8647 - 7s/epoch - 14ms/step
Epoch 5/20
469/469 - 12s - loss: 0.2900 - accuracy: 0.8922 - val_loss: 0.3841 - val_accuracy: 0.8491 - 12s/epoch - 26ms/step
Epoch 6/20
469/469 - 18s - loss: 0.2747 - accuracy: 0.8971 - val_loss: 0.3825 - val_accuracy: 0.8651 - 18s/epoch - 37ms/step
Epoch 7/20
469/469 - 18s - loss: 0.2616 - accuracy: 0.9011 - val_loss: 0.3476 - val_accuracy: 0.8784 - 18s/epoch - 38ms/step
Epoch 8/20
469/469 - 18s - loss: 0.2467 - accuracy: 0.9061 - val_loss: 0.3354 - val_accuracy: 0.8883 - 18s/epoch - 38ms/step
Epoch 9/

In [11]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

ypred=model.predict(xtest)


ypred =(ypred>0.5) #convering contineous to labels
list(ypred)




313/313 [==============================] - 1s 4ms/step


[array([False, False, False, False, False, False, False, False, False,
         True]),
 array([False, False,  True, False, False, False, False, False, False,
        False]),
 array([False,  True, False, False, False, False, False, False, False,
        False]),
 array([False,  True, False, False, False, False, False, False, False,
        False]),
 array([False, False, False, False, False, False,  True, False, False,
        False]),
 array([False,  True, False, False, False, False, False, False, False,
        False]),
 array([False, False, False, False,  True, False, False, False, False,
        False]),
 array([False, False, False, False, False, False,  True, False, False,
        False]),
 array([False, False, False, False, False,  True, False, False, False,
        False]),
 array([False, False, False, False, False, False, False,  True, False,
        False]),
 array([False, False, False, False,  True, False, False, False, False,
        False]),
 array([False, False, False, Fal

In [39]:
print('classificatio report:\n',classification_report(ytest,ypred))

classificatio report:
               precision    recall  f1-score   support

           0       0.84      0.85      0.85      1000
           1       1.00      0.97      0.98      1000
           2       0.75      0.86      0.80      1000
           3       0.88      0.92      0.90      1000
           4       0.83      0.77      0.80      1000
           5       0.99      0.95      0.97      1000
           6       0.84      0.58      0.69      1000
           7       0.94      0.97      0.96      1000
           8       0.99      0.96      0.97      1000
           9       0.95      0.97      0.96      1000

   micro avg       0.90      0.88      0.89     10000
   macro avg       0.90      0.88      0.89     10000
weighted avg       0.90      0.88      0.89     10000
 samples avg       0.88      0.88      0.88     10000



C:\Users\Vishnu\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [42]:
from sklearn.metrics import multilabel_confusion_matrix

print('confusion matrix:\n', multilabel_confusion_matrix(ytest, ypred))


confusion matrix:
 [[[8841  159]
  [ 148  852]]

 [[8996    4]
  [  29  971]]

 [[8715  285]
  [ 142  858]]

 [[8872  128]
  [  83  917]]

 [[8848  152]
  [ 234  766]]

 [[8993    7]
  [  51  949]]

 [[8885  115]
  [ 417  583]]

 [[8940   60]
  [  31  969]]

 [[8988   12]
  [  41  959]]

 [[8952   48]
  [  30  970]]]
