# 1. What is the purpose of text preprocessing in NLP, and why is it essential before analysis?

# 2. Describe tokenization in NLP and explain its significance in text processing.

In [10]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize

text="""Tokenization involves dividing text into smaller components such as words, phrases, or characters. This process is essential for various natural language processing tasks, as it provides organized input for analysis. Tokenization plays a crucial role in tasks like sentiment analysis, language translation, and information retrieval, enabling better language understanding, feature extraction, and model comprehension."""
print('Original text:\n',text)
print()
tokenised_sent=sent_tokenize(text)
print('Aftr sentence Tokanization:\n',tokenised_sent)
print()
print('no of sentnces:\n',len(tokenised_sent))
print('='*70)
print()

print('Original text:\n',text)
print()
tokenised_word=word_tokenize(text)
print('Aftr word Tokanization:\n',tokenised_word)
print()
print('no of words:\n',len(tokenised_word))

Original text:
 Tokenization involves dividing text into smaller components such as words, phrases, or characters. This process is essential for various natural language processing tasks, as it provides organized input for analysis. Tokenization plays a crucial role in tasks like sentiment analysis, language translation, and information retrieval, enabling better language understanding, feature extraction, and model comprehension.

Aftr sentence Tokanization:
 ['Tokenization involves dividing text into smaller components such as words, phrases, or characters.', 'This process is essential for various natural language processing tasks, as it provides organized input for analysis.', 'Tokenization plays a crucial role in tasks like sentiment analysis, language translation, and information retrieval, enabling better language understanding, feature extraction, and model comprehension.']

no of sentnces:
 3

Original text:
 Tokenization involves dividing text into smaller components such as w

# 3. What are the differences between stemming and lemmatization in NLP? When would you choose one over the other?

In [8]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\jagad\AppData\Roaming\nltk_data...


True

In [11]:
from nltk.stem import PorterStemmer

ps=PorterStemmer()

stemmed_words=[]

for w in tokenised_word:
    stemmed_words.append(ps.stem(w))
    

print('='*70)
print('Tokenized words - without stemming:\n\n\t',tokenised_word)
print('='*70)
print('\nTokenized words - afer stemming are:\n\t',stemmed_words)

from nltk.stem import WordNetLemmatizer

#Initilize the wordnet lemmatizer
lemma=WordNetLemmatizer()

#apply lemmatazion to each word
lemma_words=[lemma.lemmatize(word,pos='v') for word in tokenised_word ]

print('='*70)
print('lemmarized words:\n',lemma_words)

Tokenized words - without stemming:

	 ['Tokenization', 'involves', 'dividing', 'text', 'into', 'smaller', 'components', 'such', 'as', 'words', ',', 'phrases', ',', 'or', 'characters', '.', 'This', 'process', 'is', 'essential', 'for', 'various', 'natural', 'language', 'processing', 'tasks', ',', 'as', 'it', 'provides', 'organized', 'input', 'for', 'analysis', '.', 'Tokenization', 'plays', 'a', 'crucial', 'role', 'in', 'tasks', 'like', 'sentiment', 'analysis', ',', 'language', 'translation', ',', 'and', 'information', 'retrieval', ',', 'enabling', 'better', 'language', 'understanding', ',', 'feature', 'extraction', ',', 'and', 'model', 'comprehension', '.']

Tokenized words - afer stemming are:
	 ['token', 'involv', 'divid', 'text', 'into', 'smaller', 'compon', 'such', 'as', 'word', ',', 'phrase', ',', 'or', 'charact', '.', 'thi', 'process', 'is', 'essenti', 'for', 'variou', 'natur', 'languag', 'process', 'task', ',', 'as', 'it', 'provid', 'organ', 'input', 'for', 'analysi', '.', 'token

# 4. Explain the concept of stop words and their role in text preprocessing. How do they impact NLP tasks?

In [12]:
from nltk.corpus import stopwords
stop_words=set(stopwords.words('english'))

filtered_tokens=[]
for w in tokenised_word:
    if w not in stop_words:
        filtered_tokens.append(w)
print('Length of words:\t',len(tokenised_word))
print('='*70)
print('Tokenized words - with stop words:\n\n\t',tokenised_word)
print('='*70)
print('Length after the remoal of stopwords:\t',len(filtered_tokens))
print('='*70)
print('\nTokenized words - afer removing the stopwords are:\n\t',filtered_tokens)

Length of words:	 65
Tokenized words - with stop words:

	 ['Tokenization', 'involves', 'dividing', 'text', 'into', 'smaller', 'components', 'such', 'as', 'words', ',', 'phrases', ',', 'or', 'characters', '.', 'This', 'process', 'is', 'essential', 'for', 'various', 'natural', 'language', 'processing', 'tasks', ',', 'as', 'it', 'provides', 'organized', 'input', 'for', 'analysis', '.', 'Tokenization', 'plays', 'a', 'crucial', 'role', 'in', 'tasks', 'like', 'sentiment', 'analysis', ',', 'language', 'translation', ',', 'and', 'information', 'retrieval', ',', 'enabling', 'better', 'language', 'understanding', ',', 'feature', 'extraction', ',', 'and', 'model', 'comprehension', '.']
Length after the remoal of stopwords:	 52

Tokenized words - afer removing the stopwords are:
	 ['Tokenization', 'involves', 'dividing', 'text', 'smaller', 'components', 'words', ',', 'phrases', ',', 'characters', '.', 'This', 'process', 'essential', 'various', 'natural', 'language', 'processing', 'tasks', ',', 'p

# 5. How does the process of removing punctuation contribute to text preprocessing in NLP? What are its benefits?

In [13]:
words=[word for word in tokenised_word if word.isalpha()]

print('Original text:\n',text)
print('='*70)

print('after removing puntuations:\n')
print(words)

Original text:
 Tokenization involves dividing text into smaller components such as words, phrases, or characters. This process is essential for various natural language processing tasks, as it provides organized input for analysis. Tokenization plays a crucial role in tasks like sentiment analysis, language translation, and information retrieval, enabling better language understanding, feature extraction, and model comprehension.
after removing puntuations:

['Tokenization', 'involves', 'dividing', 'text', 'into', 'smaller', 'components', 'such', 'as', 'words', 'phrases', 'or', 'characters', 'This', 'process', 'is', 'essential', 'for', 'various', 'natural', 'language', 'processing', 'tasks', 'as', 'it', 'provides', 'organized', 'input', 'for', 'analysis', 'Tokenization', 'plays', 'a', 'crucial', 'role', 'in', 'tasks', 'like', 'sentiment', 'analysis', 'language', 'translation', 'and', 'information', 'retrieval', 'enabling', 'better', 'language', 'understanding', 'feature', 'extraction'

# 6. Discuss the importance of lowercase conversion in text preprocessing. Why is it a common step in NLP tasks?

In [14]:
lower_words=[word.lower() for word in tokenised_word]
print('Original text:\n',text)
print('='*70)

print('after lowering the case:\n')
print(lower_words)

Original text:
 Tokenization involves dividing text into smaller components such as words, phrases, or characters. This process is essential for various natural language processing tasks, as it provides organized input for analysis. Tokenization plays a crucial role in tasks like sentiment analysis, language translation, and information retrieval, enabling better language understanding, feature extraction, and model comprehension.
after lowering the case:

['tokenization', 'involves', 'dividing', 'text', 'into', 'smaller', 'components', 'such', 'as', 'words', ',', 'phrases', ',', 'or', 'characters', '.', 'this', 'process', 'is', 'essential', 'for', 'various', 'natural', 'language', 'processing', 'tasks', ',', 'as', 'it', 'provides', 'organized', 'input', 'for', 'analysis', '.', 'tokenization', 'plays', 'a', 'crucial', 'role', 'in', 'tasks', 'like', 'sentiment', 'analysis', ',', 'language', 'translation', ',', 'and', 'information', 'retrieval', ',', 'enabling', 'better', 'language', 'un

# 7. Explain the term "vectorization" concerning text data. How does techniques like CountVectorizer contribute to text preprocessing in NLP?

In [15]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

vector=CountVectorizer()

x=vector.fit_transform(tokenised_word)

feature_names=vector.get_feature_names_out()

print('Feature names:\n',feature_names)
print('*'*70)
print('Token counts matrix:')
print(x.toarray())

Feature names:
 ['analysis' 'and' 'as' 'better' 'characters' 'components' 'comprehension'
 'crucial' 'dividing' 'enabling' 'essential' 'extraction' 'feature' 'for'
 'in' 'information' 'input' 'into' 'involves' 'is' 'it' 'language' 'like'
 'model' 'natural' 'or' 'organized' 'phrases' 'plays' 'process'
 'processing' 'provides' 'retrieval' 'role' 'sentiment' 'smaller' 'such'
 'tasks' 'text' 'this' 'tokenization' 'translation' 'understanding'
 'various' 'words']
**********************************************************************
Token counts matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# 8. Describe the concept of normalization in NLP. Provide examples of normalization techniques used in text preprocessing.